import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/tailwind.css";
import Container from "./components/container";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen
        flex flex-col
        bg-neutral-900 text-neutral-200`}
      >
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
