import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Container from "./components/container";
import Footer from "./components/footer";
import Header from "./components/header";
import Inner from "./components/inner";
import Main from "./components/main";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-900 text-neutral-200
        min-h-screen text-center`}
      >
        <Container>
          <Header />
          <Inner>
            <Sidebar />
            <Main>{children}</Main>
          </Inner>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
