import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/tailwind.css";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prisma Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}
        min-h-screen flex flex-col
      bg-neutral-950 text-neutral-200`}
      >
        <Header />
        <div className="flex-1 flex justify-center">{children}</div>
      </body>
    </html>
  );
}
